name: sentiment_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - jupyter
  - pip
  - pip:
    - tensorflow
    - transformers
